# Generated by Django 2.1 on 2018-08-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armstimetable', '0007_auto_20180802_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default='2018-08-15 09:00:25'),
        ),
    ]
